#!/bin/bash
set -euo pipefail

# Pinned tool versions
DIFF_SO_FANCY_VERSION="v1.4.10"
TLDR_COMMIT="7d57134c2ab58eb5c906f31bdf695e653f5d128b"

usage() {
  cmd=$(basename "$0")
  profiles=$(ls -1 profiles/)
  cat <<EOF

Automatically sets up symbolic links in the home directory.
Configures settings and plugins.

USAGE: ./$cmd [options]
$cmd [-p|--profile]
Specify an environment profile. Default: "default"
Available profiles:
$(printf '  %s\n' $profiles)

$cmd [-h|--help]
Print this help message

EOF
  exit 0
}

profile="default"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -p|--profile)
      if [[ $# -lt 2 ]]; then
        echo "Error: --profile requires a value"
        exit 1
      fi
      profile="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      usage
      ;;
  esac
done

cd "$(dirname "${BASH_SOURCE[0]}")"
rootDir=$(pwd)

if [ ! -d "$rootDir/profiles/$profile" ]; then
  echo "Unknown profile \"$profile\". Available profiles:"
  ls -1 profiles/
  exit 1
fi

echo "Setting up with profile=$profile"

##########################
# Dotfiles
##########################

echo "-----------------------------"
echo "Installing dotfiles"
echo "-----------------------------"
ln -sf "$rootDir/.bashrc" ~/.bashrc
ln -sf "$rootDir/.vimrc" ~/.vimrc
ln -sf "$rootDir/.gitconfig" ~/.gitconfig
ln -sf "$rootDir/.tmux.conf" ~/.tmux.conf
mkdir -p ~/.config
ln -sf "$rootDir/.config/nvim" ~/.config/nvim

echo "-----------------------------"
echo "Installing profile: $profile"
echo "-----------------------------"
for file in "$rootDir/profiles/$profile"/.*; do
  [ -f "$file" ] || continue
  ln -sf "$file" "$HOME/$(basename "$file")"
done

#########################
# Plugins and tools
#########################

mkdir -p ~/bin
export PATH="$HOME/bin:$PATH"

echo "-----------------------------"
echo "Installing vim-plug"
echo "-----------------------------"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "Reload .vimrc and run :PlugInstall to install vim plugins."

echo "-----------------------------"
echo "Installing tmux"
echo "-----------------------------"
if command -v tmux >/dev/null 2>&1; then
  echo "tmux already installed: $(tmux -V)"
else
  echo "tmux not found. Install it with your package manager (e.g. sudo apt install tmux)."
fi

echo "-----------------------------"
echo "Installing tpm"
echo "-----------------------------"
if [ -d ~/.tmux/plugins/tpm ]; then
  echo "tpm already installed"
else
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
echo "In tmux, enter prefix + I to install plugins"

echo "-----------------------------"
echo "Installing tldr (commit ${TLDR_COMMIT:0:7})"
echo "-----------------------------"
tmpdir=$(mktemp -d)
git clone --quiet https://github.com/raylee/tldr-sh-client.git "$tmpdir/tldr-sh-client"
git -C "$tmpdir/tldr-sh-client" checkout --quiet "$TLDR_COMMIT"
cp "$tmpdir/tldr-sh-client/tldr" ~/bin/
chmod +x ~/bin/tldr
rm -rf "$tmpdir"

echo "-----------------------------"
echo "Installing diff-so-fancy $DIFF_SO_FANCY_VERSION"
echo "-----------------------------"
tmpdir=$(mktemp -d)
git clone --quiet --depth 1 --branch "$DIFF_SO_FANCY_VERSION" \
    https://github.com/so-fancy/diff-so-fancy.git "$tmpdir/diff-so-fancy"
cp "$tmpdir/diff-so-fancy/diff-so-fancy" ~/bin/
chmod +x ~/bin/diff-so-fancy
rm -rf "$tmpdir"

echo "-----------------------------"
echo "Installing fzf"
echo "-----------------------------"
if command -v fzf >/dev/null 2>&1; then
  echo "fzf already installed: $(fzf --version)"
else
  sudo apt-get install -y fzf
fi

cat > ~/.fzf.bash <<'EOF'
# Setup fzf (apt package)
# Auto-generated by setup.sh
FZF_SHELL="/usr/share/doc/fzf/examples"

# Auto-completion
# ---------------
[[ $- == *i* ]] && [ -f "$FZF_SHELL/completion.bash" ] && source "$FZF_SHELL/completion.bash"

# Key bindings
# ------------
[ -f "$FZF_SHELL/key-bindings.bash" ] && source "$FZF_SHELL/key-bindings.bash"
EOF

echo "-----------------------------"
echo "Setup complete"
echo "-----------------------------"
